export const COLORS = {
  ATHENS_GRAY: '#F6F6F9',
  SEA_GREEN: '#31A063',
  DUSTY_GRAY: '#999999',
}

export const THEME_COLORS = {
  MAIN_COLOR: COLORS.SEA_GREEN,
  INACTIVE_COLOR: COLORS.DUSTY_GRAY,
  MAIN_BACKGROUND: COLORS.ATHENS_GRAY,
}
